title: Huwaida Nur Asysyifa Mufarrida
logo: /assets/img/headshot_circle.png
avatar: https://github.com/huwaidanur/portfolio_huwai/blob/main/foto_formal.png
show_downloads: true
theme: jekyll-theme-minimal
